### ISSUE TITLE
标题已删除

### ISSUE THREAD

**Issue by vay007** [D-CDC/go-uniswap#1]
看到文章后，这里有点不明白，能细说一下吗。

**Comment by kericfrank** [comment]
合约格式改变了生成的bincode会变，算出来的hash也不一样。createPair算出来的内部逻辑不一致

**Comment by vay007** [comment]
嗯，这里弄明白了。我目前卡在自己弄私链，可以添加交易对，但是发送addLiquidityETH就报错，不知道问题，出在什么地方。

**Comment by kericfrank** [comment]
错误原因是啥

**Comment by vay007** [comment]
Error: Transaction has been reverted by the EVM:

**Comment by kericfrank** [comment]
这个错误 看不出来内部原因，用我的代码部署到私链上可以成功吗

**Comment by vay007** [comment]
我走一遍你的流程吧。我是自己弄的，太难了。
